### ISSUE TITLE
Need to install academic icons

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/kbenoit-hugo-site#1]
The references to the "ai" icons are not displaying, perhaps because they are not installed. 

See https://github.com/kbenoit/kbenoit-hugo-site/blob/master/content/authors/admin/_index.md for e.g. line 55 (`icon_pack: ai`).

Looks like Font Awesome had to be installed, e.g. in https://github.com/kbenoit/kbenoit-hugo-site/tree/master/static/assets/fonts.

@Mayazure can you install the Academic icons too please?

**Comment by Mayazure** [comment]
Ai pack can be enabled by setting the **[icon.pack]** option: **"ai = true"**, which can be found in [params.toml](https://github.com/kbenoit/kbenoit-hugo-site/blob/master/config/_default/params.toml). This is enabled now.
